### ISSUE TITLE
关于user接口的问题

### ISSUE THREAD

**Issue by ningwinn** [Yemiaojun/pet114#13]
添加用户时未考虑密码的长度，安全性（包含大小写字母数字等）问题
登陆时用户名和密码为空需要有提示
用户登陆时修改密码时，正常修改提示密码修改错误，同时存在修改后密码的长度，安全性等问题
重置密码时也需要考虑密码的长度，安全性等问题
管理员通过id修改密码时未考虑修改密码和原密码一致的问题,同时管理员可以设置空密码
更新权限时具有管理员权限时仍提示无效的权限等级，用户不存在时，提示也是无效的权限等级
删除用户时未考虑级联删除的问题，同时无法发送request

**Comment by Yemiaojun** [comment]
已处理
