### ISSUE TITLE
有关病种业务的问题

### ISSUE THREAD

**Issue by ghost** [Yemiaojun/pet114#6]
- add时没有对名字的唯一性，名字的非空性，名字的长度，以及名字的语言格式进行校验
- 更新时没有报id没有找到的报错信息，关于名字的约束同上
- 删除没找到id应报错
- id查找，没找到id无错误信息
- 用户未登录均无报错信息
- 用户未登录时能查询信息（可以不改

**Comment by Yemiaojun** [comment]
收到喵
